import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.plan.deleteMany();

  const plans = [
    // Florida - Miami-Dade
    {
      planYear: 2025, planId: "H1036-001", planName: "Aetna Medicare Advantage (HMO)", organizationName: "Aetna", planType: "HMO",
      state: "FL", county: "Miami-Dade", zipCode: "33101",
      monthlyPremium: 0, partBGivebackAmount: 45.50, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 3900, pcpCopay: 0, specialistCopay: 30, emergencyRoomCopay: 90,
      ambulanceCopay: 250, outpatientHospitalCopay: 250, hospitalStayCopay: "$275/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $194.50/day days 21-100",
      mriCopay: 200, catScanCopay: 200, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 10,
      drugTier3Copay: 47, drugTier4Copay: 100, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 120, foodCardAllowance: 100, dentalBenefits: "Comprehensive dental - $2,500 max",
      hearingBenefits: "$1,500 hearing aid allowance every year", visionBenefits: "$250 eyewear allowance",
      transportationBenefit: "24 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H5216-003", planName: "Humana Gold Plus (HMO)", organizationName: "Humana", planType: "HMO",
      state: "FL", county: "Miami-Dade", zipCode: "33101",
      monthlyPremium: 0, partBGivebackAmount: 80.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 3400, pcpCopay: 0, specialistCopay: 25, emergencyRoomCopay: 90,
      ambulanceCopay: 275, outpatientHospitalCopay: 200, hospitalStayCopay: "$250/day days 1-6", skilledNursingCopay: "$0/day days 1-20, $188/day days 21-100",
      mriCopay: 150, catScanCopay: 175, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 5,
      drugTier3Copay: 42, drugTier4Copay: 95, drugTier5Copay: 275, drugTier6Copay: null,
      otcAllowance: 150, foodCardAllowance: 125, dentalBenefits: "Comprehensive dental - $3,000 max",
      hearingBenefits: "$2,000 hearing aid allowance every 2 years", visionBenefits: "$300 eyewear allowance",
      transportationBenefit: "36 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H1748-001", planName: "UnitedHealthcare Dual Complete (HMO D-SNP)", organizationName: "UnitedHealthcare", planType: "HMO",
      state: "FL", county: "Miami-Dade", zipCode: "33101",
      monthlyPremium: 0, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "Full", medicaidLevel: "QMB",
      medicalDeductible: 0, maxOutOfPocket: 3400, pcpCopay: 0, specialistCopay: 0, emergencyRoomCopay: 0,
      ambulanceCopay: 0, outpatientHospitalCopay: 0, hospitalStayCopay: "$0/day", skilledNursingCopay: "$0/day",
      mriCopay: 0, catScanCopay: 0, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 0,
      drugTier3Copay: 0, drugTier4Copay: 0, drugTier5Copay: 0, drugTier6Copay: null,
      otcAllowance: 300, foodCardAllowance: 200, dentalBenefits: "Comprehensive dental - $4,000 max",
      hearingBenefits: "$2,500 hearing aid allowance every year", visionBenefits: "$400 eyewear allowance",
      transportationBenefit: "48 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H5521-020", planName: "Devoted Health Medicare Advantage (HMO)", organizationName: "Devoted Health", planType: "HMO",
      state: "FL", county: "Miami-Dade", zipCode: "33101",
      monthlyPremium: 0, partBGivebackAmount: 60.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 4500, pcpCopay: 0, specialistCopay: 35, emergencyRoomCopay: 90,
      ambulanceCopay: 250, outpatientHospitalCopay: 300, hospitalStayCopay: "$300/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $200/day days 21-100",
      mriCopay: 225, catScanCopay: 225, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 8,
      drugTier3Copay: 45, drugTier4Copay: 100, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 100, foodCardAllowance: 75, dentalBenefits: "Preventive dental only",
      hearingBenefits: "$1,000 hearing aid allowance every 2 years", visionBenefits: "$200 eyewear allowance",
      transportationBenefit: "12 one-way trips per year",
    },
    // Florida - Broward
    {
      planYear: 2025, planId: "H1036-002", planName: "Aetna Medicare Value (PPO)", organizationName: "Aetna", planType: "PPO",
      state: "FL", county: "Broward", zipCode: "33301",
      monthlyPremium: 25, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 100, maxOutOfPocket: 5900, pcpCopay: 5, specialistCopay: 40, emergencyRoomCopay: 90,
      ambulanceCopay: 275, outpatientHospitalCopay: 350, hospitalStayCopay: "$325/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $194.50/day days 21-100",
      mriCopay: 250, catScanCopay: 250, drugDeductible: 100, drugTier1Copay: 2, drugTier2Copay: 12,
      drugTier3Copay: 47, drugTier4Copay: 100, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 60, foodCardAllowance: 0, dentalBenefits: "Preventive dental only",
      hearingBenefits: "$500 hearing aid allowance every 2 years", visionBenefits: "$150 eyewear allowance",
      transportationBenefit: "None",
    },
    {
      planYear: 2025, planId: "H5216-004", planName: "Humana Honor (PPO)", organizationName: "Humana", planType: "PPO",
      state: "FL", county: "Broward", zipCode: "33301",
      monthlyPremium: 0, partBGivebackAmount: 30.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 4200, pcpCopay: 0, specialistCopay: 30, emergencyRoomCopay: 90,
      ambulanceCopay: 250, outpatientHospitalCopay: 275, hospitalStayCopay: "$275/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $188/day days 21-100",
      mriCopay: 175, catScanCopay: 175, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 8,
      drugTier3Copay: 40, drugTier4Copay: 90, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 100, foodCardAllowance: 75, dentalBenefits: "Comprehensive dental - $2,000 max",
      hearingBenefits: "$1,500 hearing aid allowance every year", visionBenefits: "$250 eyewear allowance",
      transportationBenefit: "24 one-way trips per year",
    },
    // Texas - Harris
    {
      planYear: 2025, planId: "H4590-001", planName: "Cigna Medicare Advantage (HMO)", organizationName: "Cigna", planType: "HMO",
      state: "TX", county: "Harris", zipCode: "77001",
      monthlyPremium: 0, partBGivebackAmount: 25.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 4900, pcpCopay: 5, specialistCopay: 40, emergencyRoomCopay: 90,
      ambulanceCopay: 275, outpatientHospitalCopay: 300, hospitalStayCopay: "$300/day days 1-6", skilledNursingCopay: "$0/day days 1-20, $194.50/day days 21-100",
      mriCopay: 200, catScanCopay: 200, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 10,
      drugTier3Copay: 47, drugTier4Copay: 100, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 75, foodCardAllowance: 50, dentalBenefits: "Comprehensive dental - $1,500 max",
      hearingBenefits: "$1,000 hearing aid allowance every 2 years", visionBenefits: "$200 eyewear allowance",
      transportationBenefit: "12 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H1748-010", planName: "UnitedHealthcare Medicare Advantage (PPO)", organizationName: "UnitedHealthcare", planType: "PPO",
      state: "TX", county: "Harris", zipCode: "77001",
      monthlyPremium: 0, partBGivebackAmount: 50.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 4500, pcpCopay: 0, specialistCopay: 35, emergencyRoomCopay: 90,
      ambulanceCopay: 250, outpatientHospitalCopay: 250, hospitalStayCopay: "$250/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $188/day days 21-100",
      mriCopay: 175, catScanCopay: 175, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 7,
      drugTier3Copay: 42, drugTier4Copay: 95, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 120, foodCardAllowance: 100, dentalBenefits: "Comprehensive dental - $2,500 max",
      hearingBenefits: "$1,500 hearing aid allowance every year", visionBenefits: "$275 eyewear allowance",
      transportationBenefit: "24 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H5216-020", planName: "Humana Dual Eligible (HMO D-SNP)", organizationName: "Humana", planType: "HMO",
      state: "TX", county: "Harris", zipCode: "77001",
      monthlyPremium: 0, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "Full", medicaidLevel: "SLMB",
      medicalDeductible: 0, maxOutOfPocket: 3200, pcpCopay: 0, specialistCopay: 0, emergencyRoomCopay: 0,
      ambulanceCopay: 0, outpatientHospitalCopay: 0, hospitalStayCopay: "$0/day", skilledNursingCopay: "$0/day",
      mriCopay: 0, catScanCopay: 0, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 0,
      drugTier3Copay: 0, drugTier4Copay: 0, drugTier5Copay: 0, drugTier6Copay: null,
      otcAllowance: 250, foodCardAllowance: 175, dentalBenefits: "Comprehensive dental - $3,500 max",
      hearingBenefits: "$2,000 hearing aid allowance every year", visionBenefits: "$350 eyewear allowance",
      transportationBenefit: "48 one-way trips per year",
    },
    // Texas - Dallas
    {
      planYear: 2025, planId: "H4590-005", planName: "Cigna True Choice (PPO)", organizationName: "Cigna", planType: "PPO",
      state: "TX", county: "Dallas", zipCode: "75201",
      monthlyPremium: 15, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 50, maxOutOfPocket: 5500, pcpCopay: 10, specialistCopay: 45, emergencyRoomCopay: 90,
      ambulanceCopay: 300, outpatientHospitalCopay: 350, hospitalStayCopay: "$350/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $194.50/day days 21-100",
      mriCopay: 250, catScanCopay: 225, drugDeductible: 50, drugTier1Copay: 1, drugTier2Copay: 10,
      drugTier3Copay: 47, drugTier4Copay: 100, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 50, foodCardAllowance: 0, dentalBenefits: "Preventive dental only",
      hearingBenefits: "$500 hearing aid allowance every 2 years", visionBenefits: "$100 eyewear allowance",
      transportationBenefit: "None",
    },
    // California - Los Angeles
    {
      planYear: 2025, planId: "H0543-001", planName: "SCAN Health Plan (HMO)", organizationName: "SCAN Health Plan", planType: "HMO",
      state: "CA", county: "Los Angeles", zipCode: "90001",
      monthlyPremium: 0, partBGivebackAmount: 70.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 3400, pcpCopay: 0, specialistCopay: 20, emergencyRoomCopay: 90,
      ambulanceCopay: 200, outpatientHospitalCopay: 200, hospitalStayCopay: "$225/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $188/day days 21-100",
      mriCopay: 150, catScanCopay: 150, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 5,
      drugTier3Copay: 38, drugTier4Copay: 85, drugTier5Copay: 225, drugTier6Copay: null,
      otcAllowance: 150, foodCardAllowance: 100, dentalBenefits: "Comprehensive dental - $3,000 max",
      hearingBenefits: "$2,500 hearing aid allowance every year", visionBenefits: "$350 eyewear allowance",
      transportationBenefit: "36 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H0562-001", planName: "Kaiser Permanente Senior Advantage (HMO)", organizationName: "Kaiser Permanente", planType: "HMO",
      state: "CA", county: "Los Angeles", zipCode: "90001",
      monthlyPremium: 0, partBGivebackAmount: 90.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 2900, pcpCopay: 0, specialistCopay: 15, emergencyRoomCopay: 65,
      ambulanceCopay: 150, outpatientHospitalCopay: 150, hospitalStayCopay: "$200/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $175/day days 21-100",
      mriCopay: 100, catScanCopay: 100, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 5,
      drugTier3Copay: 35, drugTier4Copay: 80, drugTier5Copay: 200, drugTier6Copay: null,
      otcAllowance: 200, foodCardAllowance: 150, dentalBenefits: "Comprehensive dental - $3,500 max",
      hearingBenefits: "$3,000 hearing aid allowance every year", visionBenefits: "$400 eyewear allowance",
      transportationBenefit: "48 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H5928-001", planName: "Blue Shield Medicare (PPO)", organizationName: "Blue Shield of CA", planType: "PPO",
      state: "CA", county: "Los Angeles", zipCode: "90001",
      monthlyPremium: 35, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 150, maxOutOfPocket: 6700, pcpCopay: 10, specialistCopay: 50, emergencyRoomCopay: 90,
      ambulanceCopay: 300, outpatientHospitalCopay: 400, hospitalStayCopay: "$400/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $194.50/day days 21-100",
      mriCopay: 300, catScanCopay: 275, drugDeductible: 150, drugTier1Copay: 5, drugTier2Copay: 15,
      drugTier3Copay: 47, drugTier4Copay: 100, drugTier5Copay: 275, drugTier6Copay: 33,
      otcAllowance: 25, foodCardAllowance: 0, dentalBenefits: "Preventive dental only",
      hearingBenefits: "None", visionBenefits: "$100 eyewear allowance",
      transportationBenefit: "None",
    },
    // New York - Kings (Brooklyn)
    {
      planYear: 2025, planId: "H3359-001", planName: "Healthfirst Medicare (HMO)", organizationName: "Healthfirst", planType: "HMO",
      state: "NY", county: "Kings", zipCode: "11201",
      monthlyPremium: 0, partBGivebackAmount: 100.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 2900, pcpCopay: 0, specialistCopay: 15, emergencyRoomCopay: 65,
      ambulanceCopay: 150, outpatientHospitalCopay: 175, hospitalStayCopay: "$200/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $175/day days 21-100",
      mriCopay: 100, catScanCopay: 100, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 3,
      drugTier3Copay: 35, drugTier4Copay: 80, drugTier5Copay: 200, drugTier6Copay: null,
      otcAllowance: 200, foodCardAllowance: 175, dentalBenefits: "Comprehensive dental - $4,000 max",
      hearingBenefits: "$3,000 hearing aid allowance every year", visionBenefits: "$400 eyewear allowance",
      transportationBenefit: "48 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H3347-001", planName: "EmblemHealth VIP (HMO)", organizationName: "EmblemHealth", planType: "HMO",
      state: "NY", county: "Kings", zipCode: "11201",
      monthlyPremium: 0, partBGivebackAmount: 65.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 3900, pcpCopay: 0, specialistCopay: 25, emergencyRoomCopay: 90,
      ambulanceCopay: 225, outpatientHospitalCopay: 250, hospitalStayCopay: "$275/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $188/day days 21-100",
      mriCopay: 175, catScanCopay: 175, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 7,
      drugTier3Copay: 42, drugTier4Copay: 95, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 100, foodCardAllowance: 100, dentalBenefits: "Comprehensive dental - $2,500 max",
      hearingBenefits: "$1,500 hearing aid allowance every year", visionBenefits: "$250 eyewear allowance",
      transportationBenefit: "24 one-way trips per year",
    },
    // New York - New York (Manhattan)
    {
      planYear: 2025, planId: "H3359-010", planName: "Healthfirst Dual Advantage (HMO D-SNP)", organizationName: "Healthfirst", planType: "HMO",
      state: "NY", county: "New York", zipCode: "10001",
      monthlyPremium: 0, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "Full", medicaidLevel: "QMB Plus",
      medicalDeductible: 0, maxOutOfPocket: 2400, pcpCopay: 0, specialistCopay: 0, emergencyRoomCopay: 0,
      ambulanceCopay: 0, outpatientHospitalCopay: 0, hospitalStayCopay: "$0/day", skilledNursingCopay: "$0/day",
      mriCopay: 0, catScanCopay: 0, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 0,
      drugTier3Copay: 0, drugTier4Copay: 0, drugTier5Copay: 0, drugTier6Copay: null,
      otcAllowance: 350, foodCardAllowance: 250, dentalBenefits: "Comprehensive dental - $5,000 max",
      hearingBenefits: "$3,000 hearing aid allowance every year", visionBenefits: "$500 eyewear allowance",
      transportationBenefit: "60 one-way trips per year",
    },
    // Pennsylvania - Philadelphia
    {
      planYear: 2025, planId: "H3916-001", planName: "Independence Blue Cross Medicare (HMO)", organizationName: "Independence Blue Cross", planType: "HMO",
      state: "PA", county: "Philadelphia", zipCode: "19101",
      monthlyPremium: 0, partBGivebackAmount: 40.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 4200, pcpCopay: 0, specialistCopay: 30, emergencyRoomCopay: 90,
      ambulanceCopay: 250, outpatientHospitalCopay: 275, hospitalStayCopay: "$275/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $188/day days 21-100",
      mriCopay: 200, catScanCopay: 175, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 8,
      drugTier3Copay: 42, drugTier4Copay: 95, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 100, foodCardAllowance: 75, dentalBenefits: "Comprehensive dental - $2,000 max",
      hearingBenefits: "$1,500 hearing aid allowance every year", visionBenefits: "$250 eyewear allowance",
      transportationBenefit: "24 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H3916-005", planName: "Keystone Health Plan East Medicare (HMO)", organizationName: "Independence Blue Cross", planType: "HMO",
      state: "PA", county: "Philadelphia", zipCode: "19101",
      monthlyPremium: 20, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "Partial", medicaidLevel: "None",
      medicalDeductible: 75, maxOutOfPocket: 5200, pcpCopay: 10, specialistCopay: 40, emergencyRoomCopay: 90,
      ambulanceCopay: 275, outpatientHospitalCopay: 325, hospitalStayCopay: "$325/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $194.50/day days 21-100",
      mriCopay: 250, catScanCopay: 225, drugDeductible: 75, drugTier1Copay: 2, drugTier2Copay: 12,
      drugTier3Copay: 47, drugTier4Copay: 100, drugTier5Copay: 275, drugTier6Copay: 30,
      otcAllowance: 50, foodCardAllowance: 0, dentalBenefits: "Preventive dental only",
      hearingBenefits: "$750 hearing aid allowance every 2 years", visionBenefits: "$150 eyewear allowance",
      transportationBenefit: "12 one-way trips per year",
    },
    // Ohio - Cuyahoga
    {
      planYear: 2025, planId: "H2108-001", planName: "Medical Mutual Medicare Advantage (PPO)", organizationName: "Medical Mutual", planType: "PPO",
      state: "OH", county: "Cuyahoga", zipCode: "44101",
      monthlyPremium: 0, partBGivebackAmount: 35.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 4500, pcpCopay: 5, specialistCopay: 35, emergencyRoomCopay: 90,
      ambulanceCopay: 250, outpatientHospitalCopay: 275, hospitalStayCopay: "$275/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $188/day days 21-100",
      mriCopay: 200, catScanCopay: 175, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 8,
      drugTier3Copay: 42, drugTier4Copay: 95, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 100, foodCardAllowance: 50, dentalBenefits: "Comprehensive dental - $2,000 max",
      hearingBenefits: "$1,500 hearing aid allowance every year", visionBenefits: "$250 eyewear allowance",
      transportationBenefit: "24 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H1748-030", planName: "UnitedHealthcare Dual Complete (HMO D-SNP)", organizationName: "UnitedHealthcare", planType: "HMO",
      state: "OH", county: "Cuyahoga", zipCode: "44101",
      monthlyPremium: 0, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "Full", medicaidLevel: "QMB",
      medicalDeductible: 0, maxOutOfPocket: 3000, pcpCopay: 0, specialistCopay: 0, emergencyRoomCopay: 0,
      ambulanceCopay: 0, outpatientHospitalCopay: 0, hospitalStayCopay: "$0/day", skilledNursingCopay: "$0/day",
      mriCopay: 0, catScanCopay: 0, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 0,
      drugTier3Copay: 0, drugTier4Copay: 0, drugTier5Copay: 0, drugTier6Copay: null,
      otcAllowance: 275, foodCardAllowance: 200, dentalBenefits: "Comprehensive dental - $4,000 max",
      hearingBenefits: "$2,500 hearing aid allowance every year", visionBenefits: "$400 eyewear allowance",
      transportationBenefit: "48 one-way trips per year",
    },
    // Arizona - Maricopa
    {
      planYear: 2025, planId: "H0354-001", planName: "Banner Medicare Advantage (HMO)", organizationName: "Banner Health", planType: "HMO",
      state: "AZ", county: "Maricopa", zipCode: "85001",
      monthlyPremium: 0, partBGivebackAmount: 55.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 3800, pcpCopay: 0, specialistCopay: 25, emergencyRoomCopay: 90,
      ambulanceCopay: 225, outpatientHospitalCopay: 225, hospitalStayCopay: "$250/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $188/day days 21-100",
      mriCopay: 150, catScanCopay: 150, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 7,
      drugTier3Copay: 40, drugTier4Copay: 90, drugTier5Copay: 225, drugTier6Copay: null,
      otcAllowance: 125, foodCardAllowance: 100, dentalBenefits: "Comprehensive dental - $2,500 max",
      hearingBenefits: "$2,000 hearing aid allowance every year", visionBenefits: "$300 eyewear allowance",
      transportationBenefit: "36 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H1748-020", planName: "AARP Medicare Advantage (PPO)", organizationName: "UnitedHealthcare", planType: "PPO",
      state: "AZ", county: "Maricopa", zipCode: "85001",
      monthlyPremium: 0, partBGivebackAmount: 40.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 4200, pcpCopay: 0, specialistCopay: 30, emergencyRoomCopay: 90,
      ambulanceCopay: 250, outpatientHospitalCopay: 250, hospitalStayCopay: "$275/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $194.50/day days 21-100",
      mriCopay: 175, catScanCopay: 175, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 8,
      drugTier3Copay: 42, drugTier4Copay: 95, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 110, foodCardAllowance: 75, dentalBenefits: "Comprehensive dental - $2,000 max",
      hearingBenefits: "$1,500 hearing aid allowance every year", visionBenefits: "$250 eyewear allowance",
      transportationBenefit: "24 one-way trips per year",
    },
    // Georgia - Fulton
    {
      planYear: 2025, planId: "H5253-001", planName: "Wellcare Medicare Advantage (HMO)", organizationName: "Wellcare", planType: "HMO",
      state: "GA", county: "Fulton", zipCode: "30301",
      monthlyPremium: 0, partBGivebackAmount: 30.00, lowIncomeSubsidyLevel: "None", medicaidLevel: "None",
      medicalDeductible: 0, maxOutOfPocket: 4500, pcpCopay: 0, specialistCopay: 35, emergencyRoomCopay: 90,
      ambulanceCopay: 250, outpatientHospitalCopay: 275, hospitalStayCopay: "$300/day days 1-5", skilledNursingCopay: "$0/day days 1-20, $194.50/day days 21-100",
      mriCopay: 200, catScanCopay: 200, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 8,
      drugTier3Copay: 45, drugTier4Copay: 95, drugTier5Copay: 250, drugTier6Copay: null,
      otcAllowance: 100, foodCardAllowance: 75, dentalBenefits: "Comprehensive dental - $2,000 max",
      hearingBenefits: "$1,000 hearing aid allowance every 2 years", visionBenefits: "$200 eyewear allowance",
      transportationBenefit: "24 one-way trips per year",
    },
    {
      planYear: 2025, planId: "H5253-010", planName: "Wellcare Dual Liberty (HMO D-SNP)", organizationName: "Wellcare", planType: "HMO",
      state: "GA", county: "Fulton", zipCode: "30301",
      monthlyPremium: 0, partBGivebackAmount: 0, lowIncomeSubsidyLevel: "Full", medicaidLevel: "SLMB Plus",
      medicalDeductible: 0, maxOutOfPocket: 2800, pcpCopay: 0, specialistCopay: 0, emergencyRoomCopay: 0,
      ambulanceCopay: 0, outpatientHospitalCopay: 0, hospitalStayCopay: "$0/day", skilledNursingCopay: "$0/day",
      mriCopay: 0, catScanCopay: 0, drugDeductible: 0, drugTier1Copay: 0, drugTier2Copay: 0,
      drugTier3Copay: 0, drugTier4Copay: 0, drugTier5Copay: 0, drugTier6Copay: null,
      otcAllowance: 275, foodCardAllowance: 200, dentalBenefits: "Comprehensive dental - $3,500 max",
      hearingBenefits: "$2,500 hearing aid allowance every year", visionBenefits: "$400 eyewear allowance",
      transportationBenefit: "48 one-way trips per year",
    },
  ];

  await prisma.plan.createMany({ data: plans });
  console.log(`Seeded ${plans.length} plans`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
